<a href="https://colab.research.google.com/github/MFaiqKhan/PyTorch_colab/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals::

Resources Notebook : https://www.learnpytorch.io/00_pytorch_fundamental

In [1]:
print("Hello I am learning Machine Learning and Deep Learning")

Hello I am learning Machine Learning and Deep Learning


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__) # built in attr of pytorch modle that contains the version number of the Library


1.13.1+cu116


## Introduction to Tensors:

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` 

Usually Scalar and Vector Tensors are represented by Lower case a and y Respectively.

Matric and Tensor are represented by Upper case Q and X Respectively

In [4]:
# scalar:

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get Tensor Back from as Python int
scalar.item()

7

In [5]:
# Vector

vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [8]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([3])

In [2]:
# MATRIX

MATRIX = torch.tensor([[1,8],
                       [1,3]])
MATRIX

tensor([[1, 8],
        [1, 3]])

In [8]:
MATRIX.ndim


2

In [9]:
MATRIX[1]

tensor([1, 3])

In [3]:
MATRIX.shape


torch.Size([2, 2])

In [2]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [9,2,3],
                        [2,3,2]]])
TENSOR

tensor([[[1, 2, 3],
         [9, 2, 3],
         [2, 3, 2]]])

In [5]:
TENSOR.ndim

3

In [6]:
TENSOR.shape # Outer Bracket Contains only 1 cell, middle inner bracket contrains 3 brackets inside, and inner most bracket contains
# 3 elements

torch.Size([1, 3, 3])

In [4]:
TENSOR[0][0][0]

tensor(1)

In [6]:
### Random Tensors:

random_tensor = torch.rand(4,4)
random_tensor

tensor([[0.7367, 0.2587, 0.7154, 0.8073],
        [0.3345, 0.8894, 0.6014, 0.3908],
        [0.6791, 0.5267, 0.6967, 0.2094],
        [0.5966, 0.2157, 0.4252, 0.9778]])

In [7]:
### random tensor with similar shape to an image

random_image_tensor = torch.rand(size=(3,224,224)) # color channels, height, width
random_image_tensor.shape, random_image_tensor.ndim 

(torch.Size([3, 224, 224]), 3)

In [12]:
### Zeroes and Ones in Tensor Representation:

zeros = torch.zeros(size=(4,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [13]:
zeros * random_tensor ## size/shape of both zeros and random_tensor must be equal

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(size=(4,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32)

In [18]:
### Range of Tensors and tensors-like

one_to_ten = torch.arange(start=0, end=100, step=7)
one_to_ten, one_to_ten.shape

(tensor([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]),
 torch.Size([15]))

In [19]:
ten_zeros = torch.zeros_like(input=one_to_ten) # a tensor of all zeros with the same shape as a previous tensor.
ten_zeros
# Sometimes you might want one tensor of a certain type with the same shape as another tensor.

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

generally the default and most common is 32 bit floating point.

there are different different type of tensor datatypes: https://pytorch.org/docs/stable/tensors.html

The reason for all of these is to do with precision in computing.
Precision is the amount of detail used to describe a number.
The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

<b/>Note</b>: Tensor Datatypes is one of the 3 big errors you will find or run into with pytorch and deeplearning.

(for computing purpose both tensors should be similar to each other on 3 things)

1.) Tensors not right datatype

2.) tensors not right shape

3.) not on right device
 

In [23]:
### float 32 tensor/default

default_tensor = torch.tensor([3, 6.0, 9.0],
                                dtype = None,
                                device=None,
                                requires_grad=False)

default_tensor, default_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [24]:
### Convert it into 64 bit floating point

float_64 = default_tensor.type(torch.float64)
float_64

tensor([3., 6., 9.], dtype=torch.float64)

In [26]:
### Can two datatypes of tensor float 16 and 32 respectively be multiplied together ?

float_64 * default_tensor  ## Yes they can , but in neural networks and in some places they will bring error , so we should 
# use same datatypes 


tensor([ 9., 36., 81.], dtype=torch.float64)

In [28]:
### lets do for two different Int datatypes of tensors 

int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor * float_64 ## It works as well, so sometimes error do occur in neaural network rather than normal multiplication

tensor([ 3., 12., 27.], dtype=torch.float64)

### Getting Information from Tensors(Tensors Attributes)

1.) Tensors not right datatype, use `tensor.dtype` to get datatype of a tensor
 
2.) tensors not right shape, use `tensor.shape` to get shape
 
3.) not on right device, use `tensor.device` to get device 

In [29]:
### create a tensor:

new_tensor = torch.rand(2,2)
new_tensor

tensor([[0.7505, 0.7626],
        [0.0953, 0.1231]])

In [31]:
# print the details of the new_tensor we created above

print(new_tensor)
print(f"Dataype of tensor: {new_tensor.dtype}") ## An f-string is a string literal that allows you to include expressions inside braces {} 
# which are evaluated at runtime and replaced with their values as a part of the string. 
# This is a convenient way to construct strings that contain variables or other expressions in a concise and readable way.
print(f"Shape of tensor: {new_tensor.shape}") 
print(f"Device of tensor: {new_tensor.device}") 

tensor([[0.7505, 0.7626],
        [0.0953, 0.1231]])
Dataype of tensor: torch.float32
Shape of tensor: torch.Size([2, 2])
Device of tensor: cpu


### Manipulating Tensors (Tensor Operations)

Commonly used Tensor Operations to create a neaural network : 
- Addition
- Subtraction
- Multiplication (element-wise) (Multiple a matrix by a single number)
- Division
- Matrix Multiplication

In [3]:
# Add 10 to a tensor.
tensor = torch.tensor([2,4,5])
tensor + 10

tensor([12, 14, 15])

In [7]:
# Multiply tensor by 10

multiply_tensor = tensor * 10
multiply_tensor

tensor([20, 40, 50])

In [8]:
tensor ## It is still the same tensor we initialized above, 

tensor([2, 4, 5])

In [9]:
# Subtract 10

tensor - 10


tensor([-8, -6, -5])

In [4]:
# PyTorch in-built functions
torch.mul(tensor, 10), torch.add(tensor,10) # (Short for Multiplication etc)

(tensor([20, 40, 50]), tensor([12, 14, 15]))

### Matrix Multiplication in neural networks and deep learning:

- Element Wise Multiplication
- Multiplying One Matric with another Matric (Dot Product)

How to do Matrix Multiplication : https://www.mathsisfun.com/algebra/matrix-multiplying.html

Two Main Rules that for Matrix Multiplication : 
1. The **inner Dimensions** Must Match: (Column of first one should match the row of second one)
* `(3, 2) @ (3, 2)` won't work

* `(2, 3) @ (3, 2)` will work

* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the outer dimensions:

* `(2, 3) @ (3, 2) -> (2, 2)`

* `(3, 2) @ (2, 3) -> (3, 3)`

### Visualize Matric Multiplication by creating your own:
http://matrixmultiplication.xyz/

In [13]:
# @ symbol is another way to multiply matrices same as torch.matmul

tensor @ tensor

tensor(45)

In [5]:
# Element Wise Multiplication:

print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([2, 4, 5]) * tensor([2, 4, 5])
Equals: tensor([ 4, 16, 25])


In [6]:
# Matrix Multiplcation :
torch.matmul(tensor, tensor) # applying the matrix by matrix rule of multiply and add both.

tensor(45)

In [7]:
# Matrix multiplication by Hand
2*2 + 4*4 + 5*5


45

In [10]:
%%time 
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value) # multiplying matrix through forloop, will take longer time

tensor(45)
CPU times: user 2.01 ms, sys: 0 ns, total: 2.01 ms
Wall time: 2.02 ms


In [12]:
%%time
torch.matmul(tensor,tensor) # built-in version of torch multiplication is optimized , we should always use this rather than by hand

CPU times: user 914 µs, sys: 0 ns, total: 914 µs
Wall time: 928 µs


tensor(45)

### One of the most Commmon Errors in Deep Learning: Shape Errors

In [16]:
# Shape For Matrix Multiplication:
tensor1 = torch.tensor([[1,2,1],
                        [0,1,0],
                        [1,3,4]])

tensor2 = torch.tensor([[2,5],
                        [6,7],
                        [1,8]])

torch.matmul(tensor1, tensor2), tensor1.shape, tensor2.shape
# torch.mm(tensor1, tensor2) # torch.mm is the same as torch.matmul (It's and Alias for torch.matmul)

(tensor([[15, 27],
         [ 6,  7],
         [24, 58]]), torch.Size([3, 3]), torch.Size([3, 2]))

In [18]:
# let's do one for the error:
tensorA = torch.tensor([[1,2],
                        [0,1],
                        [1,3]])

tensorB = torch.tensor([[2,5],
                        [6,7],
                        [1,8]])

torch.mm(tensorA, tensorB) # Will return an Error

RuntimeError: ignored

In [19]:
tensorA.shape, tensorB.shape # Rule 1 is not followed here, thats why the above code gave us an error

(torch.Size([3, 2]), torch.Size([3, 2]))

In [20]:
# lets change the shape of the tensor B by arranging it applying tranpose function on it.
# Transpose  (switch the dimensions of a given tensor)

tensorB.T, tensorB.T.shape # rows into column and vice versa 

(tensor([[2, 6, 1],
         [5, 7, 8]]), torch.Size([2, 3]))

In [24]:
torch.matmul(tensorA, tensorB.T), torch.matmul(tensorA, tensorB.T).shape

(tensor([[12, 20, 17],
         [ 5,  7,  8],
         [17, 27, 25]]), torch.Size([3, 3]))

In [28]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensorA = {tensorA.shape}, tensorB = {tensorB.shape}\n")
print(f"New shapes: tensorA = {tensorA.shape} (same as above), tensorB.T = {tensorB.T.shape}\n")
print(f"Multiplying: {tensorA.shape} * {tensorB.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensorA, tensorB.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensorA = torch.Size([3, 2]), tensorB = torch.Size([3, 2])

New shapes: tensorA = torch.Size([3, 2]) (same as above), tensorB.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[12, 20, 17],
        [ 5,  7,  8],
        [17, 27, 25]])

Output shape: torch.Size([3, 3])


### Tensor Aggregation ( Finding the min, max, mean, sum etc )

Performing a calculation on whole tensor to find a certain/specfic value

In [33]:
# tensor with range:

tens = torch.arange(start=0, end=100, step=10)
tens, tens.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [32]:
# Finding the min value in above tensor:

torch.min(tens), tens.min()

(tensor(0), tensor(0))

In [35]:
# find max value:

torch.max(tens), tens.max()

(tensor(90), tensor(90))

In [37]:
# Find the Mean:

torch.mean(tens) # not the right datatype error
# the input dtype is int64 which is basically long 
# and the mean() function uses floating point or complex dtype.

RuntimeError: ignored

In [39]:
# lets convert the dtype of tensor from int64 into float32

torch.mean(tens.type(torch.float32)), tens.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [40]:
# Find the Sum:

torch.sum(tens), tens.sum()

(tensor(450), tensor(450))

### Finding the Positional Min and Max:

In [41]:
tens

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
print(f"Index where max value occurs: {tens.argmax()}")
print(f"Index where min value occurs: {tens.argmin()}")


Index where max value occurs: 9
Index where min value occurs: 0
