<a href="https://colab.research.google.com/github/MFaiqKhan/PyTorch_colab/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals::

Resources Notebook : https://www.learnpytorch.io/00_pytorch_fundamental

In [1]:
print("Hello I am learning Machine Learning and Deep Learning")

Hello I am learning Machine Learning and Deep Learning


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__) # built in attr of pytorch modle that contains the version number of the Library


1.13.1+cu116


## Introduction to Tensors:

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` 

Usually Scalar and Vector Tensors are represented by Lower case a and y Respectively.

Matric and Tensor are represented by Upper case Q and X Respectively

In [4]:
# scalar:

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get Tensor Back from as Python int
scalar.item()

7

In [5]:
# Vector

vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [8]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([3])

In [2]:
# MATRIX

MATRIX = torch.tensor([[1,8],
                       [1,3]])
MATRIX

tensor([[1, 8],
        [1, 3]])

In [8]:
MATRIX.ndim


2

In [9]:
MATRIX[1]

tensor([1, 3])

In [3]:
MATRIX.shape


torch.Size([2, 2])

In [2]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [9,2,3],
                        [2,3,2]]])
TENSOR

tensor([[[1, 2, 3],
         [9, 2, 3],
         [2, 3, 2]]])

In [5]:
TENSOR.ndim

3

In [6]:
TENSOR.shape # Outer Bracket Contains only 1 cell, middle inner bracket contrains 3 brackets inside, and inner most bracket contains
# 3 elements

torch.Size([1, 3, 3])

In [4]:
TENSOR[0][0][0]

tensor(1)

In [6]:
### Random Tensors:

random_tensor = torch.rand(4,4)
random_tensor

tensor([[0.7367, 0.2587, 0.7154, 0.8073],
        [0.3345, 0.8894, 0.6014, 0.3908],
        [0.6791, 0.5267, 0.6967, 0.2094],
        [0.5966, 0.2157, 0.4252, 0.9778]])

In [7]:
### random tensor with similar shape to an image

random_image_tensor = torch.rand(size=(3,224,224)) # color channels, height, width
random_image_tensor.shape, random_image_tensor.ndim 

(torch.Size([3, 224, 224]), 3)

In [12]:
### Zeroes and Ones in Tensor Representation:

zeros = torch.zeros(size=(4,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [13]:
zeros * random_tensor ## size/shape of both zeros and random_tensor must be equal

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(size=(4,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32)

In [18]:
### Range of Tensors and tensors-like

one_to_ten = torch.arange(start=0, end=100, step=7)
one_to_ten, one_to_ten.shape

(tensor([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]),
 torch.Size([15]))

In [19]:
ten_zeros = torch.zeros_like(input=one_to_ten) # a tensor of all zeros with the same shape as a previous tensor.
ten_zeros
# Sometimes you might want one tensor of a certain type with the same shape as another tensor.

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

generally the default and most common is 32 bit floating point.

there are different different type of tensor datatypes: https://pytorch.org/docs/stable/tensors.html

The reason for all of these is to do with precision in computing.
Precision is the amount of detail used to describe a number.
The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

<b/>Note</b>: Tensor Datatypes is one of the 3 big errors you will find or run into with pytorch and deeplearning.

(for computing purpose both tensors should be similar to each other on 3 things)

1.) Tensors not right datatype

2.) tensors not right shape

3.) not on right device
 

In [23]:
### float 32 tensor/default

default_tensor = torch.tensor([3, 6.0, 9.0],
                                dtype = None,
                                device=None,
                                requires_grad=False)

default_tensor, default_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [24]:
### Convert it into 64 bit floating point

float_64 = default_tensor.type(torch.float64)
float_64

tensor([3., 6., 9.], dtype=torch.float64)

In [26]:
### Can two datatypes of tensor float 16 and 32 respectively be multiplied together ?

float_64 * default_tensor  ## Yes they can , but in neural networks and in some places they will bring error , so we should 
# use same datatypes 


tensor([ 9., 36., 81.], dtype=torch.float64)

In [28]:
### lets do for two different Int datatypes of tensors 

int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor * float_64 ## It works as well, so sometimes error do occur in neaural network rather than normal multiplication

tensor([ 3., 12., 27.], dtype=torch.float64)

### Getting Information from Tensors(Tensors Attributes)

1.) Tensors not right datatype, use `tensor.dtype` to get datatype of a tensor
 
2.) tensors not right shape, use `tensor.shape` to get shape
 
3.) not on right device, use `tensor.device` to get device 

In [29]:
### create a tensor:

new_tensor = torch.rand(2,2)
new_tensor

tensor([[0.7505, 0.7626],
        [0.0953, 0.1231]])

In [31]:
# print the details of the new_tensor we created above

print(new_tensor)
print(f"Dataype of tensor: {new_tensor.dtype}") ## An f-string is a string literal that allows you to include expressions inside braces {} 
# which are evaluated at runtime and replaced with their values as a part of the string. 
# This is a convenient way to construct strings that contain variables or other expressions in a concise and readable way.
print(f"Shape of tensor: {new_tensor.shape}") 
print(f"Device of tensor: {new_tensor.device}") 

tensor([[0.7505, 0.7626],
        [0.0953, 0.1231]])
Dataype of tensor: torch.float32
Shape of tensor: torch.Size([2, 2])
Device of tensor: cpu


### Manipulating Tensors (Tensor Operations)

Commonly used Tensor Operations to create a neaural network : 
- Addition
- Subtraction
- Multiplication (element-wise) (Multiple a matrix by a single number)
- Division
- Matrix Multiplication

In [3]:
# Add 10 to a tensor.
tensor = torch.tensor([2,4,5])
tensor + 10

tensor([12, 14, 15])

In [7]:
# Multiply tensor by 10

multiply_tensor = tensor * 10
multiply_tensor

tensor([20, 40, 50])

In [8]:
tensor ## It is still the same tensor we initialized above, 

tensor([2, 4, 5])

In [9]:
# Subtract 10

tensor - 10


tensor([-8, -6, -5])

In [4]:
# PyTorch in-built functions
torch.mul(tensor, 10), torch.add(tensor,10) # (Short for Multiplication etc)

(tensor([20, 40, 50]), tensor([12, 14, 15]))

### Matrix Multiplication in neural networks and deep learning:

- Element Wise Multiplication
- Multiplying One Matric with another Matric (Dot Product)

How to do Matrix Multiplication : https://www.mathsisfun.com/algebra/matrix-multiplying.html

Two Main Rules that for Matrix Multiplication : 
1. The **inner Dimensions** Must Match: (Column of first one should match the row of second one)
* `(3, 2) @ (3, 2)` won't work

* `(2, 3) @ (3, 2)` will work

* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the outer dimensions:

* `(2, 3) @ (3, 2) -> (2, 2)`

* `(3, 2) @ (2, 3) -> (3, 3)`

### Visualize Matric Multiplication by creating your own:
http://matrixmultiplication.xyz/

In [13]:
# @ symbol is another way to multiply matrices same as torch.matmul

tensor @ tensor

tensor(45)

In [5]:
# Element Wise Multiplication:

print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([2, 4, 5]) * tensor([2, 4, 5])
Equals: tensor([ 4, 16, 25])


In [6]:
# Matrix Multiplcation :
torch.matmul(tensor, tensor) # applying the matrix by matrix rule of multiply and add both.

tensor(45)

In [7]:
# Matrix multiplication by Hand
2*2 + 4*4 + 5*5


45

In [10]:
%%time 
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value) # multiplying matrix through forloop, will take longer time

tensor(45)
CPU times: user 2.01 ms, sys: 0 ns, total: 2.01 ms
Wall time: 2.02 ms


In [12]:
%%time
torch.matmul(tensor,tensor) # built-in version of torch multiplication is optimized , we should always use this rather than by hand

CPU times: user 914 µs, sys: 0 ns, total: 914 µs
Wall time: 928 µs


tensor(45)

### One of the most Commmon Errors in Deep Learning: Shape Errors

In [16]:
# Shape For Matrix Multiplication:
tensor1 = torch.tensor([[1,2,1],
                        [0,1,0],
                        [1,3,4]])

tensor2 = torch.tensor([[2,5],
                        [6,7],
                        [1,8]])

torch.matmul(tensor1, tensor2), tensor1.shape, tensor2.shape
# torch.mm(tensor1, tensor2) # torch.mm is the same as torch.matmul (It's and Alias for torch.matmul)

(tensor([[15, 27],
         [ 6,  7],
         [24, 58]]), torch.Size([3, 3]), torch.Size([3, 2]))

In [18]:
# let's do one for the error:
tensorA = torch.tensor([[1,2],
                        [0,1],
                        [1,3]])

tensorB = torch.tensor([[2,5],
                        [6,7],
                        [1,8]])

torch.mm(tensorA, tensorB) # Will return an Error

RuntimeError: ignored

In [19]:
tensorA.shape, tensorB.shape # Rule 1 is not followed here, thats why the above code gave us an error

(torch.Size([3, 2]), torch.Size([3, 2]))

In [20]:
# lets change the shape of the tensor B by arranging it applying tranpose function on it.
# Transpose  (switch the dimensions of a given tensor)

tensorB.T, tensorB.T.shape # rows into column and vice versa 

(tensor([[2, 6, 1],
         [5, 7, 8]]), torch.Size([2, 3]))

In [24]:
torch.matmul(tensorA, tensorB.T), torch.matmul(tensorA, tensorB.T).shape

(tensor([[12, 20, 17],
         [ 5,  7,  8],
         [17, 27, 25]]), torch.Size([3, 3]))

In [28]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensorA = {tensorA.shape}, tensorB = {tensorB.shape}\n")
print(f"New shapes: tensorA = {tensorA.shape} (same as above), tensorB.T = {tensorB.T.shape}\n")
print(f"Multiplying: {tensorA.shape} * {tensorB.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensorA, tensorB.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensorA = torch.Size([3, 2]), tensorB = torch.Size([3, 2])

New shapes: tensorA = torch.Size([3, 2]) (same as above), tensorB.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[12, 20, 17],
        [ 5,  7,  8],
        [17, 27, 25]])

Output shape: torch.Size([3, 3])


### Tensor Aggregation ( Finding the min, max, mean, sum etc )

Performing a calculation on whole tensor to find a certain/specfic value

In [33]:
# tensor with range:

tens = torch.arange(start=0, end=100, step=10)
tens, tens.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [32]:
# Finding the min value in above tensor:

torch.min(tens), tens.min()

(tensor(0), tensor(0))

In [35]:
# find max value:

torch.max(tens), tens.max()

(tensor(90), tensor(90))

In [37]:
# Find the Mean:

torch.mean(tens) # not the right datatype error
# the input dtype is int64 which is basically long 
# and the mean() function uses floating point or complex dtype.

RuntimeError: ignored

In [39]:
# lets convert the dtype of tensor from int64 into float32

torch.mean(tens.type(torch.float32)), tens.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [40]:
# Find the Sum:

torch.sum(tens), tens.sum()

(tensor(450), tensor(450))

### Finding the Positional Min and Max:

In [41]:
tens

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
print(f"Index where max value occurs: {tens.argmax()}")
print(f"Index where min value occurs: {tens.argmin()}")


Index where max value occurs: 9
Index where min value occurs: 0


### Reshaping, Stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape, `torch.reshape(input, shape)`	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape() link: [Torch.RESHAPE](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape)
* View - Return a view of an input tensor of certain shape but keep the same memoery as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack) , `torch.stack(tensors, dim=0)`	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
link:[Torch.stack](https://pytorch.org/docs/1.9.1/generated/torch.stack.html)
link:[torch.vstack](https://pytorch.org/docs/1.9.1/generated/torch.vstack.html?highlight=torch%20vstack#torch.vstack)
link:[torch.hstack](https://pytorch.org/docs/1.9.1/generated/torch.hstack.html?highlight=torch%20hstack#torch.hstack)

* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [2]:
# creating a tensor to manipulate:

import torch
x = torch.arange(1.,10.)
x,x.shape,x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [7]:
# Add an extra dimension
y = x.reshape(1,9) # the shape should be compatible with the previous shape, otherwise it will give error
y

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [8]:
y.shape, y.ndim

(torch.Size([1, 9]), 2)

In [9]:
y = x.reshape(9,1)
y, y.shape, y.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]), 2)

In [3]:
# Change the view, using view , basically view works same as reshape but it shares the same memory as the original tensor variable

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
# changing z changes xz (because a view of a tensor shares the same memory as the original)

z[:,0] = 5 # The colon : before the comma , indicates that we want to select all rows of z, 
# while the 0 after the comma , indicates that we want to select only the elements in the first column.
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In Python, when working with two-dimensional arrays, the notation `z[:, 0]` is used to select all the elements in the first column of the array z.

The colon `:` before the comma `,` indicates that we want to select all rows of z, while the 0 after the comma `,` indicates that we want to select only the elements in the first column.

Here's an example:


```
import torch

z = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

first_column = z[:, 0]

print(first_column)
```

Output:

`tensor([1, 4, 7])`

In this example, z is a PyTorch tensor with 3 rows and 3 columns. When we run z`[:, 0]`, we are selecting all the elements in the first column of z, which are `[1, 4, 7]`.

The resulting first_column tensor contains the values of all elements in the first column of z. We can see this in the output, where we get a one-dimensional tensor with the values `[1, 4, 7]`.

Note that the resulting tensor has a different shape than the original z tensor. z had a shape of (3, 3) while first_column has a shape of (3,), which is a one-dimensional tensor with 3 elements. This is because we are selecting only one column of the original two-dimensional array.

In [31]:
# torch.stack 

x_stacked = torch.stack([x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

torch.stack() is a PyTorch function that concatenates a sequence of tensors along a new dimension, which is added to the resulting tensor. It takes a sequence of tensors as input and returns a new tensor that contains all the input tensors stacked along the specified dimension.

The torch.stack() function has two main variants:

torch.stack(tensors, dim=0): Stacks the input tensors along a new dimension with the given dimension index dim.

torch.cat(tensors, dim=0): Concatenates the input tensors along an existing dimension with the given dimension index dim.

Vertical stack (vstack) and horizontal stack (hstack) are common operations in linear algebra and matrix operations. In PyTorch, we can use torch.cat() function to perform these operations.

torch.cat(tensors, dim=0): Concatenates the input tensors along the specified dimension dim. When dim=0, torch.cat() performs a vertical stack or a row-wise concatenation of tensors. That is, it concatenates the tensors along the rows or vertically, effectively increasing the number of rows in the output tensor.

torch.cat(tensors, dim=1): Concatenates the input tensors along the specified dimension dim. When dim=1, torch.cat() performs a horizontal stack or a column-wise concatenation of tensors. That is, it concatenates the tensors along the columns or horizontally, effectively increasing the number of columns in the output tensor.

In [35]:
x_catstack = torch.cat((x,x), dim=0)
x_catstack

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
x_vstack = torch.vstack((x,x))
x_vstack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [39]:
x_hstack = torch.hstack((x,x))
x_hstack

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
# torch.squeeze() - removes all single dimensions from the tensor specified

x=torch.rand(1,1,1)
x

tensor([[[0.8011]]])

In [6]:
x.shape, x.ndim

(torch.Size([1, 1, 1]), 3)

In [14]:
x_squeezed = x.squeeze()
x_squeezed,  x.squeeze().shape, x.squeeze().ndim

(tensor(0.8011), torch.Size([]), 0)

In [16]:
# torch.unsqueeze() - adds a single dimension to the specified tensor at a specific dim (dimension)

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adding an extra dimension with unsqueezed()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: 0.8010972738265991
Previous shape: torch.Size([])

New tensor: tensor([0.8011])
New shape: torch.Size([1])


In [25]:
# Rearrange the order of axes values with torch.permute(input, dims), returns a view so values in the
# permuted tensor will be the same as the original tensor and if you change the values  in the viewl, it will change the values of the original

# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [28]:
# If change the value in a the permuted tensor or original tensor , it will effect the other as permuted tensor is a view of the original 
# sharing the same memory as the orignal one

x_original[0,0,0], x_permuted[0,0,0]

(tensor(0.4155), tensor(0.4155))

In [29]:
x_original[0,0,0] = 666656666
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(6.6666e+08), tensor(6.6666e+08))

### Indexing With PyTorch is similar to indexing with NumPy.

In [31]:
# creating a tensor:

import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [34]:
# indexing in tensor:

x[0], x[0][1] # or x[0,1] same as x[0][1]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]), tensor([4, 5, 6]))

In [36]:
# Index the most inner bracket (last dimension)

x[0][2][2], x[0,2,2]

(tensor(9), tensor(9))

In [37]:
# ":" semi colon is also used to index , basically "all" of a target dimension

x[:,0] # all of zeroth dimension

tensor([[1, 2, 3]])

In [39]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [40]:
# # Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [41]:
x[0, 1, 1]

tensor(5)

In [42]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [43]:
x[:,:,2]

tensor([[3, 6, 9]])


### PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

* `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
* `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [44]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # default datatype of numpy array is float64 while pytorch tensor have float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [46]:
#Change the value of array, what will this do tensor ?

array = array + 1
array, tensor

# It will not the change the tensor, so keep in mind that tensor is a different memory representation not same

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [47]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [48]:
# And the same rule applies as above, if you change the original tensor, the new numpy_tensor stays the same.

# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random) 

In neural networks randomness plays a huge rule, 

but the randomness they create is pseusorandomness that is, because they are designed after all. A computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

start with random numbers -> tensor operations -> try to make better (again and again and again)

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where reproducibility comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?


In [2]:
import torch 

# create two random tensors and check if they equal each other( they won't)

random_A = torch.rand(3,4)
random_B = torch.rand(3,4)

print(random_A)
print(random_B)
print(random_A == random_B) # false on every element


tensor([[0.2767, 0.6555, 0.0180, 0.9653],
        [0.0584, 0.3340, 0.3158, 0.4580],
        [0.5731, 0.7214, 0.5321, 0.2895]])
tensor([[0.1038, 0.9803, 0.3413, 0.1595],
        [0.8328, 0.3649, 0.8308, 0.9911],
        [0.3394, 0.7794, 0.6656, 0.7141]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [5]:
# Let's create some random but reproducible tensors, two random tensors with the same values.
# That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

import random

# # Set the random seed
RANDOM_SEED=43 
torch.manual_seed(seed=RANDOM_SEED)# try changing this to different values and see what happens to the numbers below
random_C = torch.rand(3,4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED)# try commenting this line out and seeing what happens
random_D = torch.rand(3,4)

print(f"Tensor C:\n{random_C}\n")
print(f"Tensor D:\n{random_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_C == random_D


Tensor C:
tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])

Tensor D:
tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running Tensors and PyTorch Objects on the GPUS (and making faster computations)

Deep learning algorithms require a lot of numerical operations.
And by default these operations are often done on a CPU (computer processing unit).
However, there's another common piece of hardware called a GPU (graphics processing unit), 
which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

Getting a GPU: https://www.learnpytorch.io/00_pytorch_fundamentals/#1-getting-a-gpu 



In [1]:
!nvidia-smi

Tue Feb 21 19:14:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P0    26W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
# Check for GPU Access with PyTorch
# You can test if PyTorch has access to a GPU using "torch.cuda.is_available()" .

import torch
torch.cuda.is_available()

# If the above outputs True, PyTorch can see and use the GPU, if it outputs False, 
# it can't see the GPU and in that case, you'll have to go back through the installation steps

True

If the above output "cuda" it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output "cpu", our PyTorch code will stick with the CPU.

Note: In PyTorch, it's best practice to write device agnostic code. This means code that'll run on CPU (always available) or GPU (if available).

If you want to do faster computing you can use a GPU but if you want to do much faster computing, you can use multiple GPUs.

You can count the number of GPUs PyTorch has access to using torch.cuda.device_count().

In [3]:
# Setting up device agnostic Code:

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count Number of Devices
torch.cuda.device_count()

1

In [5]:
## Putting tensors ( and models) on the gpu as it results in faster computations

# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [8]:
## As Numpy only works on the CPU , so we should move it back it to CPU from GPU :
# It will give error otherwise as :

# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()


TypeError: ignored

In [9]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu, tensor_on_gpu # The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.


(array([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'))