<a href="https://colab.research.google.com/github/MFaiqKhan/PyTorch_colab/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals::

Resources Notebook : https://www.learnpytorch.io/00_pytorch_fundamental

In [1]:
print("Hello I am learning Machine Learning and Deep Learning")

Hello I am learning Machine Learning and Deep Learning


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__) # built in attr of pytorch modle that contains the version number of the Library


1.13.1+cu116


## Introduction to Tensors:

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` 

Usually Scalar and Vector Tensors are represented by Lower case a and y Respectively.

Matric and Tensor are represented by Upper case Q and X Respectively

In [4]:
# scalar:

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get Tensor Back from as Python int
scalar.item()

7

In [5]:
# Vector

vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [8]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([3])

In [2]:
# MATRIX

MATRIX = torch.tensor([[1,8],
                       [1,3]])
MATRIX

tensor([[1, 8],
        [1, 3]])

In [8]:
MATRIX.ndim


2

In [9]:
MATRIX[1]

tensor([1, 3])

In [3]:
MATRIX.shape


torch.Size([2, 2])

In [2]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [9,2,3],
                        [2,3,2]]])
TENSOR

tensor([[[1, 2, 3],
         [9, 2, 3],
         [2, 3, 2]]])

In [5]:
TENSOR.ndim

3

In [6]:
TENSOR.shape # Outer Bracket Contains only 1 cell, middle inner bracket contrains 3 brackets inside, and inner most bracket contains
# 3 elements

torch.Size([1, 3, 3])

In [4]:
TENSOR[0][0][0]

tensor(1)

In [6]:
### Random Tensors:

random_tensor = torch.rand(4,4)
random_tensor

tensor([[0.7367, 0.2587, 0.7154, 0.8073],
        [0.3345, 0.8894, 0.6014, 0.3908],
        [0.6791, 0.5267, 0.6967, 0.2094],
        [0.5966, 0.2157, 0.4252, 0.9778]])

In [7]:
### random tensor with similar shape to an image

random_image_tensor = torch.rand(size=(3,224,224)) # color channels, height, width
random_image_tensor.shape, random_image_tensor.ndim 

(torch.Size([3, 224, 224]), 3)

In [12]:
### Zeroes and Ones in Tensor Representation:

zeros = torch.zeros(size=(4,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [13]:
zeros * random_tensor ## size/shape of both zeros and random_tensor must be equal

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(size=(4,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32)

In [18]:
### Range of Tensors and tensors-like

one_to_ten = torch.arange(start=0, end=100, step=7)
one_to_ten, one_to_ten.shape

(tensor([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]),
 torch.Size([15]))

In [19]:
ten_zeros = torch.zeros_like(input=one_to_ten) # a tensor of all zeros with the same shape as a previous tensor.
ten_zeros
# Sometimes you might want one tensor of a certain type with the same shape as another tensor.

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

generally the default and most common is 32 bit floating point.

there are different different type of tensor datatypes: https://pytorch.org/docs/stable/tensors.html

The reason for all of these is to do with precision in computing.
Precision is the amount of detail used to describe a number.
The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

<b/>Note</b>: Tensor Datatypes is one of the 3 big errors you will find or run into with pytorch and deeplearning.

(for computing purpose both tensors should be similar to each other on 3 things)
1.) Tensors not right datatype
2.) tensors not right shape
3.) not on right device
 

In [23]:
### float 32 tensor/default

default_tensor = torch.tensor([3, 6.0, 9.0],
                                dtype = None,
                                device=None,
                                requires_grad=False)

default_tensor, default_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [24]:
### Convert it into 64 bit floating point

float_64 = default_tensor.type(torch.float64)
float_64

tensor([3., 6., 9.], dtype=torch.float64)